export const forms = {
  general: {
    male: ['', 'Male'],
    female: ['-f', 'Female'],
    mega: [],
    alola: ['-alolan', '(Alolan)'],
    'totem': [],
    'totem-alola': [],
    galar: ['TODO', '(Galarian)'],
    gmax: ['-gigantamax', '(Gigantamax)'],
  },
  charizard: {
    'mega-x': [],
    'mega-y': [],
  },
  pikachu: {
    'rock-star': [],
    'belle': [],
    'pop-star': [],
    'phd': [],
    'libre': [],
    'cosplay': [],
    'original-cap': ['TODO', '(Original Cap)'],
    'hoenn-cap': ['TODO', '(Hoenn Cap)'],
    'sinnoh-cap': ['TODO', '(Sinnoh Cap)'],
    'unova-cap': ['TODO', '(Unova Cap)'],
    'kalos-cap': ['TODO', '(Kalos Cap)'],
    'alola-cap': ['TODO', '(Alola Cap)'],
    'partner-cap': ['TODO', '(Partner Cap)'],
    'starter': [],
    'world-cap': ['TODO', '(World Cap)'],
  },
  eevee: {
    'starter': [],
  },
  mewtwo: {
    'mega-x': [],
    'mega-y': [],
  },
  pichu: {
    'spiky-eared': [],
  },
  unown: {
    a: ['TODO', '(A)'],
    b: ['TODO', '(B)'],
    c: ['TODO', '(C)'],
    d: ['TODO', '(D)'],
    e: ['TODO', '(E)'],
    f: ['TODO', '(F)'],
    g: ['TODO', '(G)'],
    h: ['TODO', '(H)'],
    i: ['TODO', '(I)'],
    j: ['TODO', '(J)'],
    k: ['TODO', '(K)'],
    l: ['TODO', '(L)'],
    m: ['TODO', '(M)'],
    n: ['TODO', '(N)'],
    o: ['TODO', '(O)'],
    p: ['TODO', '(P)'],
    q: ['TODO', '(Q)'],
    r: ['TODO', '(R)'],
    s: ['TODO', '(S)'],
    t: ['TODO', '(T)'],
    u: ['TODO', '(U)'],
    v: ['TODO', '(V)'],
    w: ['TODO', '(W)'],
    x: ['TODO', '(X)'],
    y: ['TODO', '(Y)'],
    z: ['TODO', '(Z)'],
    exclamation : ['TODO', '(!)'],
    question: ['TODO', '(?)'],
  },
  castform: {
    sunny: ['TODO', '(Sunny)'],
    rainy: ['TODO', '(Rainy)'],
    snowy: ['TODO', '(Snowy)'],
  },
  kyogre: {
    primal: ['TODO', '(Primal)'],
  },
  groudon: {
    primal: ['TODO', '(Primal)'],
  },
  deoxys: {
    normal: ['TODO', '(Normal)'],
    attack: ['TODO', '(Attack)'],
    defense: ['TODO', '(Defense)'],
    speed: ['TODO', '(Speed)'],
  },
  burmy: {
    plant: ['TODO', '(Plant)'],
    sandy: ['TODO', '(Sandy)'],
    trash: ['TODO', '(Trash)'],
  },
  wormadam: {
    plant: ['TODO', '(Plant)'],
    sandy: ['TODO', '(Sandy)'],
    trash: ['TODO', '(Trash)'],
  },
  mothim: {
    plant: ['TODO', '(Plant)'],
    sandy: ['TODO', '(Sandy)'],
    trash: ['TODO', '(Trash)'],
  },
  cherrim: {
    overcast: ['TODO', '(Overcast)'],
    sunshine: ['TODO', '(Sunshine)'],
  },
  shellos: {
    east: ['TODO', '(East)'],
    west: ['TODO', '(West)'],
  },
  gastrodon: {
    east: ['TODO', '(East)'],
    west: ['TODO', '(West)'],
  },
  rotom: {
    heat: ['TODO', '(Heat)'],
    wash: ['TODO', '(Wash)'],
    frost: ['TODO', '(Frost)'],
    fan: ['TODO', '(Fan)'],
    mow: ['TODO', '(Mow)'],
  },
  giratina: {
    altered: ['TODO', '(Altered)'],
    origin: ['TODO', '(Origin)'],
  },
  shaymin: {
    land: ['TODO', '(Land)'],
    sky: ['TODO', '(Sky)'],
  },
  arceus: {
    normal: ['TODO', '(Normal)'],
    bug: ['TODO', '(Bug)'],
    dark: ['TODO', '(Dark)'],
    dragon: ['TODO', '(Dragon)'],
    electric: ['TODO', '(Electric)'],
    fighting: ['TODO', '(Fighting)'],
    fire: ['TODO', '(Fire)'],
    flying: ['TODO', '(Flying)'],
    ghost: ['TODO', '(Ghost)'],
    grass: ['TODO', '(Grass)'],
    ground: ['TODO', '(Ground)'],
    ice: ['TODO', '(Ice)'],
    poison: ['TODO', '(Poison)'],
    psychic: ['TODO', '(Psychic)'],
    rock: ['TODO', '(Rock)'],
    sky: ['TODO', '(Sky)'],
    steel: ['TODO', '(Steel)'],
    water: ['TODO', '(Water)'],
    unknown: [],
    fairy: ['TODO', '(Fairy)'],
  },
  basculin: {
    'red-striped': ['TODO', '(TODO)'],
    'blue-striped': ['TODO', '(TODO)'],
  },
  darmanitan: {
    standard: ['TODO', '(TODO)'],
    zen: ['TODO', '(TODO)'],
    'galar-standard': ['TODO', '(TODO)'],
    'galar-zen': ['TODO', '(TODO)'],
  },
  deerling: {
    spring: ['TODO', '(TODO)'],
    summer: ['TODO', '(TODO)'],
    autumn: ['TODO', '(TODO)'],
    winter: ['TODO', '(TODO)'],
  },
  sawsbuck: {
    spring: ['TODO', '(TODO)'],
    summer: ['TODO', '(TODO)'],
    autumn: ['TODO', '(TODO)'],
    winter: ['TODO', '(TODO)'],
  },
  tornadus: {
    incarnate: ['TODO', '(TODO)'],
    therian: ['TODO', '(TODO)'],
  },
  thundurus: {
    incarnate: ['TODO', '(TODO)'],
    therian: ['TODO', '(TODO)'],
  },
  landorus: {
    incarnate: ['TODO', '(TODO)'],
    therian: ['TODO', '(TODO)'],
  },
  kyurem: {
    black: ['TODO', '(TODO)'],
    white: ['TODO', '(TODO)'],
  },
  keldeo: {
    ordinary: ['TODO', '(TODO)'],
    resolute: ['TODO', '(TODO)'],
  },
  meloetta: {
    aria: ['TODO', '(TODO)'],
    pirouette: ['TODO', '(TODO)'],
  },
  genesect: {
    douse: ['TODO', '(TODO)'],
    shock: ['TODO', '(TODO)'],
    burn: ['TODO', '(TODO)'],
    chill: ['TODO', '(TODO)'],
  },
  greninja: {
    'battle-bond': ['TODO', '(TODO)'],
    ash: ['TODO', '(TODO)'],
  },
  scatterbug: {
    polar: ['TODO', '(TODO)'],
    tundra: ['TODO', '(TODO)'],
    continental: ['TODO', '(TODO)'],
    garden: ['TODO', '(TODO)'],
    elegant: ['TODO', '(TODO)'],
    meadow: ['TODO', '(TODO)'],
    modern: ['TODO', '(TODO)'],
    marine: ['TODO', '(TODO)'],
    archipelago: ['TODO', '(TODO)'],
    'high-plains': ['TODO', '(TODO)'],
    sandstorm: ['TODO', '(TODO)'],
    river: ['TODO', '(TODO)'],
    monsoon: ['TODO', '(TODO)'],
    savanna: ['TODO', '(TODO)'],
    sun: ['TODO', '(TODO)'],
    ocean: ['TODO', '(TODO)'],
    jungle: ['TODO', '(TODO)'],
    'icy-snow': ['TODO', '(TODO)'],
    fancy: ['TODO', '(TODO)'],
    'poke-ball': ['TODO', '(TODO)'],
  },
  spewpa: {
    polar: ['TODO', '(TODO)'],
    tundra: ['TODO', '(TODO)'],
    continental: ['TODO', '(TODO)'],
    garden: ['TODO', '(TODO)'],
    elegant: ['TODO', '(TODO)'],
    meadow: ['TODO', '(TODO)'],
    modern: ['TODO', '(TODO)'],
    marine: ['TODO', '(TODO)'],
    archipelago: ['TODO', '(TODO)'],
    'high-plains': ['TODO', '(TODO)'],
    sandstorm: ['TODO', '(TODO)'],
    river: ['TODO', '(TODO)'],
    monsoon: ['TODO', '(TODO)'],
    savanna: ['TODO', '(TODO)'],
    sun: ['TODO', '(TODO)'],
    ocean: ['TODO', '(TODO)'],
    jungle: ['TODO', '(TODO)'],
    'icy-snow': ['TODO', '(TODO)'],
    fancy: ['TODO', '(TODO)'],
    'poke-ball': ['TODO', '(TODO)'],
  },
  vivillon: {
    polar: ['TODO', '(TODO)'],
    tundra: ['TODO', '(TODO)'],
    continental: ['TODO', '(TODO)'],
    garden: ['TODO', '(TODO)'],
    elegant: ['TODO', '(TODO)'],
    meadow: ['TODO', '(TODO)'],
    modern: ['TODO', '(TODO)'],
    marine: ['TODO', '(TODO)'],
    archipelago: ['TODO', '(TODO)'],
    'high-plains': ['TODO', '(TODO)'],
    sandstorm: ['TODO', '(TODO)'],
    river: ['TODO', '(TODO)'],
    monsoon: ['TODO', '(TODO)'],
    savanna: ['TODO', '(TODO)'],
    sun: ['TODO', '(TODO)'],
    ocean: ['TODO', '(TODO)'],
    jungle: ['TODO', '(TODO)'],
    'icy-snow': ['TODO', '(TODO)'],
    fancy: ['TODO', '(TODO)'],
    'poke-ball': ['TODO', '(TODO)'],
  },
  flabebe: {
    red: ['TODO', '(TODO)'],
    yellow: ['TODO', '(TODO)'],
    orange: ['TODO', '(TODO)'],
    blue: ['TODO', '(TODO)'],
    white: ['TODO', '(TODO)'],
  },
  floette: {
    red: ['TODO', '(TODO)'],
    yellow: ['TODO', '(TODO)'],
    orange: ['TODO', '(TODO)'],
    blue: ['TODO', '(TODO)'],
    white: ['TODO', '(TODO)'],
    eternal: ['TODO', '(TODO)'],
  },
  florges: {
    red: ['TODO', '(TODO)'],
    yellow: ['TODO', '(TODO)'],
    orange: ['TODO', '(TODO)'],
    blue: ['TODO', '(TODO)'],
    white: ['TODO', '(TODO)'],
  },
  furfrou: {
    natural: ['TODO', '(TODO)'],
    heart: ['TODO', '(TODO)'],
    diamond: ['TODO', '(TODO)'],
    debutante: ['TODO', '(TODO)'],
    matron: ['TODO', '(TODO)'],
    dandy: ['TODO', '(TODO)'],
    'la-reine': ['TODO', '(TODO)'],
    kabuki: ['TODO', '(TODO)'],
    pharaoh: ['TODO', '(TODO)'],
    star: ['TODO', '(TODO)'],
  },
  aegislash: {
    shield: ['TODO', '(TODO)'],
    blade: ['TODO', '(TODO)'],
  },
  pumpkaboo: {
    average: ['TODO', '(TODO)'],
    small: ['TODO', '(TODO)'],
    large: ['TODO', '(TODO)'],
    super: ['TODO', '(TODO)'],
  },
  gourgeist: {
    average: ['TODO', '(TODO)'],
    small: ['TODO', '(TODO)'],
    large: ['TODO', '(TODO)'],
    super: ['TODO', '(TODO)'],
  },
  xerneas: {
    active: ['TODO', '(TODO)'],
    neutral: ['TODO', '(TODO)'],
  },
  zygarde: {
    '50': ['TODO', '(TODO)'],
    '10-power-construct': ['TODO', '(TODO)'],
    '50-power-construct': ['TODO', '(TODO)'],
    complete: ['TODO', '(TODO)'],
    '10': ['TODO', '(TODO)'],
  },
  hoopa: {
    confined: ['TODO', '(TODO)'],
    unbound: ['TODO', '(TODO)'],
  },
  oricorio: {
    baile: ['TODO', '(TODO)'],
    'pom-pom': ['TODO', '(TODO)'],
    pau: ['TODO', '(TODO)'],
    sensu: ['TODO', '(TODO)'],
    'own-tempo': ['TODO', '(TODO)'],
  },
  rockruff: {
    'own-tempo': ['TODO', '(TODO)'],
  },
  lycanroc: {
    midday: ['TODO', '(TODO)'],
    midnight: ['TODO', '(TODO)'],
    dusk: ['TODO', '(TODO)'],
  },
  wishiwashi : {
    solo: ['TODO', '(TODO)'],
    school: ['TODO', '(TODO)'],
  },
  silvally: {
    normal: ['TODO', '(Normal)'],
    bug: ['TODO', '(Bug)'],
    dark: ['TODO', '(Dark)'],
    dragon: ['TODO', '(Dragon)'],
    electric: ['TODO', '(Electric)'],
    fighting: ['TODO', '(Fighting)'],
    fire: ['TODO', '(Fire)'],
    flying: ['TODO', '(Flying)'],
    ghost: ['TODO', '(Ghost)'],
    grass: ['TODO', '(Grass)'],
    ground: ['TODO', '(Ground)'],
    ice: ['TODO', '(Ice)'],
    poison: ['TODO', '(Poison)'],
    psychic: ['TODO', '(Psychic)'],
    rock: ['TODO', '(Rock)'],
    sky: ['TODO', '(TODO)'],
    steel: ['TODO', '(Steel)'],
    water: ['TODO', '(Water)'],
    fairy: ['TODO', '(Fairy)'],
  },
  minior: {
    'red-meteor': ['TODO', '(TODO)'],
    'orange-meteor': ['TODO', '(TODO)'],
    'yellow-meteor': ['TODO', '(TODO)'],
    'green-meteor': ['TODO', '(TODO)'],
    'blue-meteor': ['TODO', '(TODO)'],
    'indigo-meteor': ['TODO', '(TODO)'],
    'violet-meteor': ['TODO', '(TODO)'],
    red: ['TODO', '(TODO)'],
    orange: ['TODO', '(TODO)'],
    yellow: ['TODO', '(TODO)'],
    green: ['TODO', '(TODO)'],
    blue: ['TODO', '(TODO)'],
    indigo: ['TODO', '(TODO)'],
    violet: ['TODO', '(TODO)'],
  },
  mimikyu: {
    disguised: ['', '(Disguised)'],
    busted: ['', '(Busted)'],
    'totem-disguised': [],
    'totem-busted': [],
  },
  necrozma: {
    dusk: ['TODO', '(TODO)'],
    dawn: ['TODO', '(TODO)'],
    ultra: ['TODO', '(TODO)'],
  },
  magearna: {
    original: ['TODO', '(TODO)'],
    pokeball: ['TODO', '(TODO)'],
  },
  cramorant: {
    gulping: ['TODO', '(TODO)'],
    gorging: ['TODO', '(TODO)'],
  },
  toxtricity: {
    amped: ['TODO', '(TODO)'],
    'low-key': ['TODO', '(TODO)'],
  },
  sinistea: {
    phony: ['TODO', '(TODO)'],
    antique: ['TODO', '(TODO)'],
  },
  polteageist: {
    phony: ['TODO', '(TODO)'],
    antique: ['TODO', '(TODO)'],
  },
  alcremie: {
    'vanilla-cream': ['TODO', '(TODO)'],
    'ruby-cream': ['TODO', '(TODO)'],
    'matcha-cream': ['TODO', '(TODO)'],
    'mint-cream': ['TODO', '(TODO)'],
    'lemon-cream': ['TODO', '(TODO)'],
    'salted-cream': ['TODO', '(TODO)'],
    'ruby-swirl': ['TODO', '(TODO)'],
    'caramel-swirl': ['TODO', '(TODO)'],
    'rainbow-swirl': ['TODO', '(TODO)'],
  },
  eiscue: {
    ice: ['TODO', '(TODO)'],
    noice: ['TODO', '(TODO)'],
  },
  morpeko: {
    'full-belly': ['TODO', '(TODO)'],
    hangry: ['TODO', '(TODO)'],
  },
  zacian: {
    crowned: ['TODO', '(TODO)'],
  },
  zamazenta: {
    crowned: ['TODO', '(TODO)'],
  },
  eternatus: {
    eternamax: ['TODO', '(TODO)'],
  },
  urshifu: {
    'single-strike': ['', '(Single Strike)'],
    'rapid-strike': ['', '(Rapid Strike)'],
  },
  zarude: {
    dada: ['TODO', '(TODO)'],
  },
  calyrex: {
    ice: ['TODO', '(TODO)'],
    shadow: ['TODO', '(TODO)'],
  }
}

export const balls = [
  "BEAST_BALL",
  "CHERISH_BALL",
  "DIVE_BALL",
  "DREAM_BALL",
  "DUSK_BALL",
  "FAST_BALL",
  "FEATHER_BALL_PLA",
  "FRIEND_BALL",
  "GIGATON_BALL_PLA",
  "GREAT_BALL",
  "GREAT_BALL_PLA",
  "HEAL_BALL",
  "HEAVY_BALL",
  "HEAVY_BALL_PLA",
  "JET_BALL_PLA",
  "LEADEN_BALL_PLA",
  "LEVEL_BALL",
  "LURE_BALL",
  "LUXURY_BALL",
  "MASTER_BALL",
  "MOON_BALL",
  "NEST_BALL",
  "NET_BALL",
  "ORIGIN_BALL_PLA",
  "PARK_BALL",
  "POKEBALL",
  "POKEBALL_PLA",
  "PREMIER_BALL",
  "QUICK_BALL",
  "REPEAT_BALL",
  "SAFARI_BALL",
  "TIMER_BALL",
  "ULTRA_BALL",
  "ULTRA_BALL_PLA",
  "WING_BALL_PLA"
];

export const regions = [
  'Kanto',
  'Johto',
  'Hoenn',
  'Sinnoh',
  'Unova',
  'Kalos',
  'Alola',
  'Galar',
  'Hisui',
]

export const lastInDexByRegion = [
  151,
  251,
  386,
  493,
  649,
  721,
  809,
  898,
  905,
]

export const fontAwesomeValues = {
  colors: {
    alert: '#842029',
  },
  sizes: {
    small: 'sm',
    medium: 'md',
    normal: 'lg',
    large: 'xl',
    huge: '2x',
  }
};